### ISSUE TITLE
SalvagedBats

### ISSUE THREAD

**Issue by rygastan** [7D2D/A18Mods#1]
Hi Xith, 

I don't know if it's an error or an oversight but when I open the 'mod.xml' file of the SalvagedBats mod and I find this line " <hash filename="Config\blocks.xml" hash="187a19f4404d5fe2b5510bc1767bc4f4", I think either this line is too much or there is a file missing in the mod that would be 'blocks.xml', because when I look in the config folder, I can't find this file. 

Find the same thing with folder would be 'XUi' and the file 'xui.xml' in wrote to this line <hash filename="Config\XUi\xui.xml" hash="b47d0558b4d9bd887e01f54badd7dbc5" />It would be cool if you could add these missing files if they are need.

Thx

Moreover, I find a 'localization.txt' file at the root of the mod that I think is too much and put there by mistake. 

Rygastan

**Comment by XythQ** [comment]
These are left over from A17.  I will fix for A19.

**Comment by rygastan** [comment]
ok ;) it works for now in 18.4 and very good 
----- Original Message -----

**Comment by XythQ** [comment]
closed
